### ISSUE TITLE
How to handle NaN?

### ISSUE THREAD

**Issue by emilv** [dndubins/QuickStats#2]
Continuing this from #2

> One thing I realized later was that I never test for NaN values, and they will crash the functions. I debated filtering for NaN values in the routines, but then decided that this is probably something that should be done prior to statistics.

**Comment by emilv** [comment]
In most cases ignoring NaN values in calculations makes sense. They should probably be considered invalid. One simple solution could be to sort all NaNs at the end of the array and return the number of non-NaNs from bubbleSort. That way the rest of your functions could loop the array as usual but only up to the new number.

Could this skew the statistics somehow? Both median and average should be fine since you only need to take the new number of elements into account.

**Comment by dndubins** [comment]
I added an example program, filterread.ino, to illustrate how to filter out NaN values. This program also rejects measurements outside 1.645 standard deviations of the mean, which may be handy for particularly noisy sensors, or outliers that cause trouble.

**Comment by dndubins** [comment]
I added a new routine to filter out nan and inf values. I didn't bake these into the stats routines on purpose, because the programmer should be aware of nan values - how many are there? Why are they happening? Then make the decision weather or not to filter them out, rather than to try and reduce or prevent them.
